### ISSUE TITLE
article citation 

### ISSUE THREAD

**Issue by Luoxiaoyu828** [ferrocactus/ConstrainedKMeans#1]
Hello:

I have used the code from your project. Do you have an associated article for this project? I would like to cite it. If you do, could you please provide me with the citation format? (my email: lxy@ctgu.edu.cn)

Xiaoyu Luo

**Comment by euxhenh** [comment]
Hi,

This project was first introduced in this preprint [https://www.biorxiv.org/content/10.1101/2021.03.19.436162v1](https://www.biorxiv.org/content/10.1101/2021.03.19.436162v1).

There is a peer-reviewed publication associated with this preprint [https://www.nature.com/articles/s41467-022-29744-0](https://www.nature.com/articles/s41467-022-29744-0), but we did not include Constrained KMeans in the final paper (although we may add it later to our tool named Cellar). You can cite either source.

If you are citing the latter you can use

```
@article{Hasanaj2022,
    author = {Euxhen Hasanaj and Jingtao Wang and Arjun Sarathi and Jun Ding and Ziv Bar-Joseph},
    issn = {2041-1723},
    issue = {1},
    journal = {Nature Communications 2022 13:1},
    month = {4},
    pages = {1-6},
    publisher = {Nature Publishing Group},
    title = {Interactive single-cell data analysis using Cellar},
    volume = {13},
    year = {2022},
}
```

Thank you,
Let me know if you have other questions. I am closing the issue.
